### ISSUE TITLE
When creating a repo no upstream is set up.

### ISSUE THREAD

**Issue by Bubu** [guyzmo/git-repo#99]
When I run `git lab create group/repo` the repository is successfully created online but locally I still have no remotes set up.

I started from a newly created repo without any remotes.

**Comment by guyzmo** [comment]
from the help:

```
[…]
    git-repo [--path=<path>] [-v...] <target> create [--add]
    git-repo [--path=<path>] [-v...] <target> create <user>/<repo> [--add]
[…]
Options for create:
    --add                    Add to local repository after creation
[…]
```

i.e.: if you do:

```
git lab create --add group/repo
```

it will be added to the current repository, if you're in one.

I decided to default to not change the local directory per default, because you're not necessarily creating a repository when you're in a directory you've already `git init`ed. And removing a remote is not hard, but because names are autogenerated it's not always obvious (`--add` will create two remotes, `gitlab` and `all`). 

But, if you forgot to add, it's really not a big deal, you just do one more command:

```
git lab add group/repo gitlab
```

cf the `-h` for add:

```
    git-repo [--path=<path>] [-v...] <target> add <user>/<repo> [<name>] [--tracking=<branch>] [-a]
[…]
Options for add:
    <name>                   Name to use for the remote (defaults to name of repo)
    -t,--tracking=<branch>   Makes this remote tracking for the current branch
    -a,--alone               Does not add the remote to the 'all' remote
```

I'm planning to split the huge `--help` screen into different `--help` for each subcommand, but at the time being, having them all in one place makes it easier to mold the CLI API.

Any thoughts?

**Comment by Bubu** [comment]
I must have missed that in the help output.

But I just tried again with `--add` and also the add subcommand. The result is always the following error:
`Fatal error: 'GitlabService' object has no attribute 'gl'` I'll rename the issue accordingly.

Re: default action: Can you explain what the use case/workflow for not adding a newly created repo as a remote is?

**Comment by guyzmo** [comment]
ahah, sorry, it's already being taken care of, cf #98. I'm working on releasing 1.8.1 ASAP! :-s

**Comment by guyzmo** [comment]
> Re: default action: Can you explain what the use case/workflow for not adding a newly created repo as a remote is?

Because when you do `git X create foo/bar` you're might be doing it in advance for a future code you're about to push, and you don't want to mess up another repository you might be in. And then you'd end up having repositories of two projects mixed together in a single `.git/config`, not nice.

As I considered that if you actually aimed to add the default upstream in current repository but forgot to do so, running `git lab add group/repo gitlab` wouldn't be too much of a hassle, I thought it would be a sane default to not mutate current repository when doing `create`.

**Comment by Bubu** [comment]
> oh, sorry, it's already being taken care of, cf #97 and #98. I'm working on releasing 1.8.1 ASAP! :confounded:

I see, thanks!

>  I thought it would be a sane default to not mutate current repository when doing create.

I understand your reasoning now. Would you consider changing the default behaviour when inside a local repo without remotes?

**Comment by guyzmo** [comment]
> > I thought it would be a sane default to not mutate current repository when doing create.
> I understand your reasoning now. Would you consider changing the default behaviour when inside a local repo without remotes?

yup, the only tough thing would be to correctly explain it off in the documentation. Though, it might become easier to explain when I'll refactor the CLI part of git-repo (where you'll have `git X create --help` that will have an independant help page from `git-repo --help`)

**Comment by metasean** [comment]
I'm running git-repo version 1.9.0.  When I run add (e.g. `git lab add group/project`) the remote is successfully added.  Unfortunately, there is still no upstream set.

**Comment by guyzmo** [comment]
@metasean if you do `git lab add group/project` it won't add an upstream. 

if you do `git lab add group/project upstream` it will add `group/project` *as* upstream.

and when I'll release v1.10, `git lab add upstream` will setup the upstream remote automagically.
